### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by travitch** [travitch/persistent-vector#30]
I'm preparing an interim release to fix the slicing bugs. I anticipate more changes (potentially some breaking) in future releases.

@treeowl Do you have any objections to releasing in the current state? I put the slicing primitives back in their inefficient forms to preserve API compatibility. I wrote up a changelog (which is mostly about your changes).

**Comment by treeowl** [comment]
I'd like to fix #27 first, if you don't mind.

**Comment by travitch** [comment]
Sure, no problem

**Comment by treeowl** [comment]
You have an open PR for that, and to make splitting eager. The latter might be controversial, but I think I prefer it that way.

**Comment by travitch** [comment]
Thanks! The improved `Eq` and `Ord` are much more sensible. I think I agree on the splitting - this structure is supposed to be pretty firmly on the strict side. I'll just document the strictness. If it becomes a problem we can always change it (or offer two variants).

**Comment by treeowl** [comment]
I think you should reinstate testing with old GHC versions for this release. I've gone to too much trouble making things backwards compatible to have that potentially be wasted. Let's wait till the *next* release to drop support for old stuff.

**Comment by travitch** [comment]
Okay. I turned travis-ci back on. It isn't easy to go before 7.10 in Github Actions (though we could do it).

**Comment by treeowl** [comment]
Like I said, I think we should just get everything tested once more, make a release, and then dump everything before 7.10.

**Comment by treeowl** [comment]
I think it should be ready now.

**Comment by travitch** [comment]
Thanks - I released 0.2 with various correctness fixes. This makes me feel a lot better about what is out there and it seems like a good basis for further development. I'm looking forward to factoring out the tail as a separate data type.
